ALTER TABLE finance.bank_account ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_finance_bank_account_company ON finance.bank_account USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_finance_bank_account_company_rls ON finance.bank_account USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_finance_payment_company ON finance.payment USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_finance_payment_company_rls ON finance.payment USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE finance.payment ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.attendance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.employment_contract ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.hr_department ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.hr_position ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.leave_request ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_hr_attendance_log_company ON hr.attendance_log USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_attendance_log_company_rls ON hr.attendance_log USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_employee_company ON hr.employee USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_employee_company_rls ON hr.employee USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_employment_contract_company ON hr.employment_contract USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_employment_contract_company_rls ON hr.employment_contract USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_hr_department_company ON hr.hr_department USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_hr_department_company_rls ON hr.hr_department USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_hr_position_company ON hr.hr_position USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_hr_position_company_rls ON hr.hr_position USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_leave_request_company ON hr.leave_request USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_leave_request_company_rls ON hr.leave_request USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_payroll_run_company ON hr.payroll_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_hr_payroll_run_company_rls ON hr.payroll_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE hr.payroll_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.inventory_valuation ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_inventory_inventory_valuation_company ON inventory.inventory_valuation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_inventory_valuation_company_rls ON inventory.inventory_valuation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_balance_company ON inventory.stock_balance USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_balance_company_rls ON inventory.stock_balance USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_bin_company ON inventory.stock_bin USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_bin_company_rls ON inventory.stock_bin USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_lot_balance_company ON inventory.stock_lot_balance USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_lot_balance_company_rls ON inventory.stock_lot_balance USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_lot_company ON inventory.stock_lot USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_lot_company_rls ON inventory.stock_lot USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_reservation_company ON inventory.stock_reservation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_reservation_company_rls ON inventory.stock_reservation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_transaction_company ON inventory.stock_transaction USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_transaction_company_rls ON inventory.stock_transaction USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_transfer_header_company ON inventory.stock_transfer_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stock_transfer_header_company_rls ON inventory.stock_transfer_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stocktaking_plan_company ON inventory.stocktaking_plan USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stocktaking_plan_company_rls ON inventory.stocktaking_plan USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stocktaking_result_company ON inventory.stocktaking_result USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_stocktaking_result_company_rls ON inventory.stocktaking_result USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_storage_location_company ON inventory.storage_location USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_storage_location_company_rls ON inventory.storage_location USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_warehouse_company ON inventory.warehouse USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_inventory_warehouse_company_rls ON inventory.warehouse USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE inventory.stock_balance ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_bin ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_lot ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_lot_balance ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_reservation ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_transaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_transfer_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stocktaking_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stocktaking_result ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.storage_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.warehouse ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.bom_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.manufacturing_cost_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.manufacturing_execution ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.mps_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.mrp_run ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_manufacturing_bom_header_company ON manufacturing.bom_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_bom_header_company_rls ON manufacturing.bom_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_manufacturing_cost_snapshot_company ON manufacturing.manufacturing_cost_snapshot USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_manufacturing_cost_snapshot_company_rls ON manufacturing.manufacturing_cost_snapshot USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_manufacturing_execution_company ON manufacturing.manufacturing_execution USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_manufacturing_execution_company_rls ON manufacturing.manufacturing_execution USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_mps_run_company ON manufacturing.mps_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_mps_run_company_rls ON manufacturing.mps_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_mrp_run_company ON manufacturing.mrp_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_mrp_run_company_rls ON manufacturing.mrp_run USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_process_master_company ON manufacturing.process_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_process_master_company_rls ON manufacturing.process_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_routing_header_company ON manufacturing.routing_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_routing_header_company_rls ON manufacturing.routing_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_work_order_company ON manufacturing.work_order USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_work_order_company_rls ON manufacturing.work_order USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_yield_metric_company ON manufacturing.yield_metric USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_manufacturing_yield_metric_company_rls ON manufacturing.yield_metric USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE manufacturing.process_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.routing_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.work_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing.yield_metric ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_purchase_purchase_invoice_company ON purchase.purchase_invoice USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_invoice_company_rls ON purchase.purchase_invoice USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_order_header_company ON purchase.purchase_order_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_order_header_company_rls ON purchase.purchase_order_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_quotation_company ON purchase.purchase_quotation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_quotation_company_rls ON purchase.purchase_quotation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_receipt_company ON purchase.purchase_receipt USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_receipt_company_rls ON purchase.purchase_receipt USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_requisition_company ON purchase.purchase_requisition USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_requisition_company_rls ON purchase.purchase_requisition USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_three_way_match_company ON purchase.purchase_three_way_match USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_purchase_three_way_match_company_rls ON purchase.purchase_three_way_match USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_supplier_item_price_company ON purchase.supplier_item_price USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_supplier_item_price_company_rls ON purchase.supplier_item_price USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_supplier_master_company ON purchase.supplier_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_purchase_supplier_master_company_rls ON purchase.supplier_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE purchase.purchase_invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.purchase_order_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.purchase_quotation ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.purchase_receipt ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.purchase_requisition ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.purchase_three_way_match ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.supplier_item_price ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase.supplier_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.billing_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.invoice_pdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.item ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.item_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.item_price_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.order_header ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_quotation_order_link_company ON sales.quotation_order_link USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_billing_header_company ON sales.billing_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_billing_header_company_rls ON sales.billing_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_customer_company ON sales.customer USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_customer_company_rls ON sales.customer USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_invoice_pdf_company ON sales.invoice_pdf USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_invoice_pdf_company_rls ON sales.invoice_pdf USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_category_company ON sales.item_category USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_category_company_rls ON sales.item_category USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_company ON sales.item USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_company_rls ON sales.item USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_price_master_company ON sales.item_price_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_item_price_master_company_rls ON sales.item_price_master USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_order_header_company ON sales.order_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_order_header_company_rls ON sales.order_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_return_header_company ON sales.return_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_return_header_company_rls ON sales.return_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_sales_quotation_company ON sales.sales_quotation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_sales_quotation_company_rls ON sales.sales_quotation USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_shipping_header_company ON sales.shipping_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_sales_shipping_header_company_rls ON sales.shipping_header USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
CREATE POLICY p_shipping_revision_company ON sales.shipping_revision USING ((company_id = public.my_company_id())) WITH CHECK ((company_id = public.my_company_id()));
ALTER TABLE sales.quotation_order_link ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.return_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.sales_quotation ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.shipping_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.shipping_revision ENABLE ROW LEVEL SECURITY;
